api_platform:
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']

  swagger:
    api_keys:
      access_token:
        name: Authorization
        type: header

when@prod:
  api_platform:
    enable_docs: false
    enable_entrypoint: false
    enable_swagger: false
    enable_swagger_ui: false

